/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.compassview;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollProxy;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.titanium.TiC;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;
import org.appcelerator.titanium.util.TiConvert;
import org.appcelerator.titanium.proxy.TiViewProxy;
import org.appcelerator.titanium.view.TiCompositeLayout;
import org.appcelerator.titanium.view.TiCompositeLayout.LayoutArrangement;
import org.appcelerator.titanium.view.TiUIView;

import android.app.Activity;
import android.content.Context;
import android.hardware.Sensor;
import android.hardware.SensorEvent;
import android.hardware.SensorEventListener;
import android.hardware.SensorManager;
import android.view.animation.Animation;
import android.view.animation.RotateAnimation;

// This proxy can be created by calling Compassview.createExample({message: "hello world"})
@Kroll.proxy(creatableInModule = CompassviewModule.class)
public class CompassViewProxy extends TiViewProxy implements
		SensorEventListener {
	// Standard Debugging variables
	TiUIView view;
	private float currentDegree = 0f;

	private static final String LCAT = "ExampleProxy";
	private static Context ctx = TiApplication.getInstance()
			.getApplicationContext();
	private static SensorManager sensorManager = (SensorManager) ctx
			.getSystemService(ctx.SENSOR_SERVICE);
	private static final boolean DBG = TiConfig.LOGD;

	private class CompassView extends TiUIView {

		private float currentDegree = 0f;

		public CompassView(TiViewProxy proxy) {
			super(proxy);

			LayoutArrangement arrangement = LayoutArrangement.DEFAULT;

			if (proxy.hasProperty(TiC.PROPERTY_LAYOUT)) {
				String layoutProperty = TiConvert.toString(proxy
						.getProperty(TiC.PROPERTY_LAYOUT));
				if (layoutProperty.equals(TiC.LAYOUT_HORIZONTAL)) {
					arrangement = LayoutArrangement.HORIZONTAL;
				} else if (layoutProperty.equals(TiC.LAYOUT_VERTICAL)) {
					arrangement = LayoutArrangement.VERTICAL;
				}
			}
			setNativeView(new TiCompositeLayout(proxy.getActivity(),
					arrangement));
		}

	}

	// Constructor
	public CompassViewProxy() {
		super();
	}

	@Override
	public TiUIView createView(Activity activity) {
		view = new CompassView(this);
		view.getLayoutParams().autoFillsHeight = true;
		view.getLayoutParams().autoFillsWidth = true;
		return view;
	}

	// Handle creation options
	@Override
	public void handleCreationDict(KrollDict opts) {
		super.handleCreationDict(opts);

		if (opts.containsKey(TiC.PROPERTY_IMAGE)) {
			Log.d(LCAT,
					"example created with message: "
							+ opts.get(TiC.PROPERTY_IMAGE));
		}
		if (opts.containsKey("offset")) {
			Log.d(LCAT,
					"example created with message: " + opts.getInt("offset"));
		}
	}

	@SuppressWarnings("deprecation")
	@Override
	public void onResume(Activity a) {
		super.onResume(a);
		sensorManager.registerListener(this,
				sensorManager.getDefaultSensor(Sensor.TYPE_ORIENTATION),
				SensorManager.SENSOR_DELAY_GAME);
	}

	@Override
	public void onPause(Activity a) {
		super.onPause(a);

		// to stop the listener and save battery

		sensorManager.unregisterListener(this);

	}

	@Override
	public void onAccuracyChanged(Sensor arg0, int arg1) {
		// TODO Auto-generated method stub

	}

	@Override
	public void onSensorChanged(SensorEvent event) {
		float degree = Math.round(event.values[0]);
		RotateAnimation ra = new RotateAnimation(currentDegree, -degree,
				Animation.RELATIVE_TO_SELF, 0.5f, Animation.RELATIVE_TO_SELF,
				0.5f);
		// how long the animation will take place
		ra.setDuration(210);
		ra.setFillAfter(true);
		view.setAnimatedRotationDegrees(-degree);
		// startAnimation(ra);
		currentDegree = -degree;

	}

}